### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by dantrevino** [universelabs/meta#67]
**Describe the bug**
Could not install meta.  

**To Reproduce**
1. npm install @universelabs/meta

**Expected behavior**
Install meta library

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser Chrome
 - Version 75.0.3770.42 (Official Build) beta (64-bit)

**Additional context**
```
 ~/projects/universe-auth  npm i @universelabs/meta
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ENODATA: Cache input stream was empty
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code EINTEGRITY
npm ERR! errno EINTEGRITY
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/copyright-update: Integrity verification failed for sha512-O9pKvkXbgdRCA5hH/NfcV36+wf0fZp1bDvdOKjhE1iiI+Dq8Bw3ybk1hsN5ZOvb/ZiI3PsxS5aBDoT+BfoZv7Q== (/home/dantrevino/.npm/_cacache/content-v2/sha512/3b/da/4abe45db81d442039847fcd7dc577ebec1fd1f669d5b0ef74e2a3844d62888f83abc070df26e4d61b0de593af6ff6622373ecc52e5a043a13f817e866fed)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dantrevino/.npm/_logs/2019-05-21T07_12_58_716Z-debug.log
```
contents of the above debug.log
---
```
...
27 verbose stack FetchError: Invalid response body while trying to fetch https://registry.npmjs.org/copyright-update: Integrity verification failed for sha512-O9pKvkXbgdRCA5hH/NfcV36+wf0fZp1bDvdOKjhE1iiI+Dq8Bw3ybk1hsN5ZOvb/ZiI3PsxS5aBDoT+BfoZv7Q== (/home/dantrevino/.npm/_cacache/content-v2/sha512/3b/da/4abe45db81d442039847fcd7dc577ebec1fd1f669d5b0ef74e2a3844d62888f83abc070df26e4d61b0de593af6ff6622373ecc52e5a043a13f817e866fed)
27 verbose stack     at Readable.body.on.err (/home/dantrevino/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:195:14)
27 verbose stack     at Readable.emit (events.js:182:13)
27 verbose stack     at cacache.get.byDigest.then.err (/home/dantrevino/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/make-fetch-happen/cache.js:94:30)
27 verbose stack     at tryCatcher (/home/dantrevino/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
27 verbose stack     at Promise._settlePromiseFromHandler (/home/dantrevino/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
27 verbose stack     at Promise._settlePromise (/home/dantrevino/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
27 verbose stack     at Promise._settlePromise0 (/home/dantrevino/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
27 verbose stack     at Promise._settlePromises (/home/dantrevino/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:689:18)
27 verbose stack     at Async._drainQueue (/home/dantrevino/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
27 verbose stack     at Async._drainQueues (/home/dantrevino/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
27 verbose stack     at Immediate.Async.drainQueues (/home/dantrevino/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
27 verbose stack     at runCallback (timers.js:705:18)
27 verbose stack     at tryOnImmediate (timers.js:676:5)
27 verbose stack     at processImmediate (timers.js:658:5)
28 verbose cwd /home/dantrevino/projects/universe-auth
29 verbose Linux 4.19.34-04457-g5b63d4390e96
30 verbose argv "/home/dantrevino/.nvm/versions/node/v10.15.0/bin/node" "/home/dantrevino/.nvm/versions/node/v10.15.0/bin/npm" "i" "@universelabs/meta"
31 verbose node v10.15.0
32 verbose npm  v6.4.1
33 error code EINTEGRITY
34 error errno EINTEGRITY
35 error Invalid response body while trying to fetch https://registry.npmjs.org/copyright-update: Integrity verification failed for sha512-O9pKvkXbgdRCA5hH/NfcV36+wf0fZp1bDvdOKjhE1iiI+Dq8Bw3ybk1hsN5ZOvb/ZiI3PsxS5aBDoT+BfoZv7Q== (/home/dantrevino/.npm/_cacache/content-v2/sha512/3b/da/4abe45db81d442039847fcd7dc577ebec1fd1f669d5b0ef74e2a3844d62888f83abc070df26e4d61b0de593af6ff6622373ecc52e5a043a13f817e866fed)
36 verbose exit [ 1, true ]
```

**Comment by guylepage3** [comment]
I added a feature yesterday and installed the update just fine. @dantrevino can you try running the installer again?
`npm i @universelabs/meta`

**Comment by dantrevino** [comment]
Running it again was the first thing I did.

fixed with `npm cache clean --force`
